# Generated by Django 4.1.6 on 2023-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='Title of Your Todo')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done?')),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
